name: Deploy the code to development environment on dev Push 

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - run: cd FormDefinitionServiceLambda && mvn clean install
      - run: cd FormDefinitionServiceLambda && mvn clean package shade:shade
      - run: mkdir staging && cp FormDefinitionServiceLambda/target/FormDefinitionServiceLambda-1.0-SNAPSHOT-shaded.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging