name: Build, Package, and Deploy (Dev)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and package Java Lambda function (FormDefinitionServiceLambda)
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
          
      # Install CDK CLI before deployment
      - name: Install CDK CLI
        run: npm install -g aws-cdk
        
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package Lambda function
        run: cd FormDefinitionServiceLambda && mvn clean install -DskipTests

      - name: Package Lambda function with shade plugin
        run: cd FormDefinitionServiceLambda && mvn clean package shade:shade

      - name: Create staging directory
        run: mkdir staging

      - name: Copy JAR file to staging directory
        run: cp /home/runner/work/github-action-jar/github-action-jar/FormDefinitionServiceLambda/target/FormDefinitionServiceLambda-*.jar staging/

      # Deploy using CDK (FormDefinitionServiceCdk)
      - name: Install CDK Toolkit
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Deploy CDK stack (dev environment)
        run: cdk deploy DevStack -c environment=dev  # Replace DevStack with your stack name

      - uses: actions/upload-artifact@v4
        with:
          name: Lambda-Package
          path: staging/*.jar
